name: CI-for-edf

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        
      - name: setup compilation env
        run: |
          python -m pip install --upgrade pip
          IF (Test-Path -Path gui/requirements.txt) {
              pip install -r gui/requirements.txt
          }
          IF (Test-Path -Path Attacks/Modbus_packet_attack/ConvertToExe/requirements.txt) {
              pip install -r Attacks/Modbus_packet_attack/ConvertToExe/requirements.txt
          }
          pip install pyinstaller
          pip install auto-py-to-exe
          pip install pyuac
          pip install pydivert

      - name: compile gui and push
        run: |
          pyinstaller --clean --noconfirm --onefile --console --add-data "gui/img;img/"  "gui/HiJack.py"
          Move-Item dist\HiJack.exe gui\ -Force
          Remove-Item -Path dist -Recurse
          Remove-Item -Path build -Recurse
          git config --global user.name "NinjaBot"
          git config --global user.email "NinjaBot-actions@users.noreply.github.com"
          git add --all
          git fetch
          git pull
          git diff-index --quiet HEAD || git commit -am "NinjaBot compiled with <3 new files for u"
          git push
        
      - name: compile malware and push
        run: |
          pyinstaller --clean --noconfirm --onefile --windowed --icon "Attacks/Modbus_packet_attack/ConvertToExe/malware_icon.ico"  "Attacks/Modbus_packet_attack/ConvertToExe/malware.pyw"
          Move-Item dist\malware.exe Attacks\Modbus_packet_attack\ConvertToExe -Force
          Remove-Item -Path Attacks/Modbus_packet_attack/ConvertToExe/malwar3.exe 
          Rename-Item -Force -Path "Attacks/Modbus_packet_attack/ConvertToExe/malware.exe" -NewName "malwar3.exe"
          Remove-Item -Path dist -Recurse
          Remove-Item -Path build -Recurse
          git config --global user.name "NinjaBot"
          git config --global user.email "NinjaBot-actions@users.noreply.github.com"
          git add --all
          git fetch
          git pull
          git diff-index --quiet HEAD || git commit -am "NinjaBot compiled with <3 new files for u"
          git push
