name: CI-for-edf

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        
      - name: setup compilation env
        run: |
          python -m pip install --upgrade pip
          IF (Test-Path -Path gui/requirements.txt) {
              pip install -r gui/requirements.txt
          }
          IF (Test-Path -Path Attacks/Modbus_packet_attack/ConvertToExe/requirements.txt) {
              pip install -r Attacks/Modbus_packet_attack/ConvertToExe/requirements.txt
          }
          pip install pyinstaller
          pip install auto-py-to-exe

      - name: compile gui
        run: |
          pyinstaller --noconfirm --onefile --console --add-data "gui/img;img/"  "gui/HiJack.py"
